/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMenuModulos;

/**
 * Ventana Menu de Modulos disppnibles
 * 
 * @author AndresGutierrez_AndresBarahona_JosePabloBarrantes
 * @version 1.0
 */
public class MenuModulos extends javax.swing.JFrame {

    /**
     * Creates new form MenuModulos
     */
    public MenuModulos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnModuloAdministrador = new javax.swing.JButton();
        btnAgenteModuloBR = new javax.swing.JButton();
        btnModuloUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Modulos");

        btnModuloAdministrador.setText("Módulo Administrador");
        btnModuloAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloAdministradorActionPerformed(evt);
            }
        });

        btnAgenteModuloBR.setText("Módulo Agentes Bienes Raíces");
        btnAgenteModuloBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenteModuloBRActionPerformed(evt);
            }
        });

        btnModuloUsuarios.setText("Módulo Usuarios Clientes");
        btnModuloUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloUsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnModuloAdministrador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnAgenteModuloBR)))
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnModuloUsuarios)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btnModuloAdministrador)
                .addGap(38, 38, 38)
                .addComponent(btnAgenteModuloBR)
                .addGap(31, 31, 31)
                .addComponent(btnModuloUsuarios)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModuloAdministradorActionPerformed

    private void btnAgenteModuloBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenteModuloBRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgenteModuloBRActionPerformed

    private void btnModuloUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModuloUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        MenuModulos ventana = new MenuModulos();
        ControladorMenuModulos controlador = new ControladorMenuModulos(ventana);
        
        ventana.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgenteModuloBR;
    public javax.swing.JButton btnModuloAdministrador;
    public javax.swing.JButton btnModuloUsuarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
